[package]
name = "ssh_host"
version = "0.1.0"
authors = ["Zacharie Corniere <zacharie.corniere@epitech.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
